architect:
  - yegor256
docker:
  image: yegor256/rultor-image:1.18.0
assets:
  credentials: yegor256/objectionary-secrets#crates-credentials
install: |
  pdd --file=/dev/null
merge:
  script: |
    cargo --color=never test
    cargo --color=never fmt --check
    cargo clippy
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1

    sed -i -e "s/^version = \"0.0.0\"/version = \"${tag}\"/" Cargo.toml
    cargo --color=never test
    cargo --color=never fmt --check
    cargo clippy
    git commit -am "${tag}"
    mkdir -p ~/.cargo && cp ../credentials ~/.cargo
    cargo --color=never publish
