# SPDX-FileCopyrightText: Copyright (c) 2022 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: tarpaulin
'on':
  push:
  pull_request:
jobs:
  check:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin --version 0.22.0
      - name: Run tests with coverage
        run: cargo tarpaulin --out Xml --all-features --exclude-files src/lib.rs -- --test-threads 1
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
