# SPDX-FileCopyrightText: Copyright (c) 2022 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: tarpaulin
'on':
  push:
  pull_request:
jobs:
  check:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.22.0'
          args: '--all-features --exclude-files src/lib.rs -- --test-threads 1'
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
